### ISSUE TITLE
No cn_map_erase

### ISSUE THREAD

**Issue by cflemmon** [iDestyKK/CN_Map#1]
There is no functionality for removing from a map. I can create a map and add to it; however, elements cannot be removed. This would be a good function to consider.

**Comment by iDestyKK** [comment]
Hi! Yes, currently the red-black trees in this implementation only have insert functionality. However, I will implement the deletion/erase functionality soon.

**Comment by AZHenley** [comment]
How soon?

**Comment by iDestyKK** [comment]
Now. 👍
